version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: p2p-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: p2p_marketplace
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - p2p-network

  # Backend API
  backend:
    build: ./backend
    container_name: p2p-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/p2p_marketplace?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      RAZORPAY_KEY_ID: rzp_test_demo_key_id
      RAZORPAY_KEY_SECRET: demo_secret_key
      RAZORPAY_WEBHOOK_SECRET: demo_webhook_secret
      PAYMENT_MODE: mock
      DEMO_MODE: true
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - p2p-network
    command: npm run dev

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: p2p-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_RAZORPAY_KEY_ID: rzp_test_demo_key_id
      VITE_PAYMENT_MODE: mock
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - p2p-network
    command: npm run dev

volumes:
  mongodb_data:

networks:
  p2p-network:
    driver: bridge
